/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels_admin;

import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import ventanas.login;
/**
 *
 * @author oli
 */
public class p_home extends javax.swing.JPanel {
    /**
     * Creates new form p_home
     */
    public p_home() {
        initComponents();
        jLabel17.setBackground(Color.red);
        
       
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        label3 = new java.awt.Label();
        jPanel6 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setForeground(new java.awt.Color(0, 153, 255));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgiso/Designer.png"))); // NOI18N
        jLabel19.setText("                          ");
        jLabel19.setToolTipText("");
        jPanel2.add(jLabel19, java.awt.BorderLayout.LINE_END);

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Georgia", 3, 65)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Usuario");
        jPanel8.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Georgia", 3, 65)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Bienvenido");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 0, 447, -1));

        jPanel2.add(jPanel8, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("   ");
        jPanel3.add(jLabel4, java.awt.BorderLayout.PAGE_END);

        jLabel5.setText("              ");
        jPanel3.add(jLabel5, java.awt.BorderLayout.LINE_END);

        jLabel6.setText("                ");
        jPanel3.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new java.awt.GridLayout(3, 4, 30, 0));

        jLabel7.setText(" ");
        jPanel5.add(jLabel7);

        jLabel8.setText(" ");
        jPanel5.add(jLabel8);

        jLabel10.setText(" ");
        jPanel5.add(jLabel10);

        jLabel13.setText(" ");
        jPanel5.add(jLabel13);

        jLabel9.setText(" ");
        jPanel5.add(jLabel9);

        jPanel7.setBackground(new java.awt.Color(227, 242, 253));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        jPanel7.setForeground(new java.awt.Color(51, 51, 51));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel17.setBackground(new java.awt.Color(255, 51, 51));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgiso/farmacia.png"))); // NOI18N
        jPanel7.add(jLabel17, java.awt.BorderLayout.CENTER);

        label3.setAlignment(java.awt.Label.CENTER);
        label3.setBackground(new java.awt.Color(227, 242, 253));
        label3.setFont(new java.awt.Font("Futura", 3, 18)); // NOI18N
        label3.setForeground(new java.awt.Color(51, 51, 51));
        label3.setText("Venta Rápida");
        jPanel7.add(label3, java.awt.BorderLayout.PAGE_END);

        jPanel5.add(jPanel7);

        jPanel6.setBackground(new java.awt.Color(227, 242, 253));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 3, true));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgiso/farmacia-online.png"))); // NOI18N
        jPanel6.add(jLabel18, java.awt.BorderLayout.CENTER);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setBackground(new java.awt.Color(227, 242, 253));
        label1.setFont(new java.awt.Font("Futura", 3, 18)); // NOI18N
        label1.setForeground(new java.awt.Color(51, 51, 51));
        label1.setText("Buscar");
        jPanel6.add(label1, java.awt.BorderLayout.PAGE_END);
        label1.getAccessibleContext().setAccessibleName("Jpanel6");

        jPanel5.add(jPanel6);

        jLabel11.setText(" ");
        jPanel5.add(jLabel11);

        jLabel12.setText(" ");
        jPanel5.add(jLabel12);

        jLabel14.setText(" ");
        jPanel5.add(jLabel14);

        jLabel16.setText(" ");
        jPanel5.add(jLabel16);

        jLabel15.setText(" ");
        jPanel5.add(jLabel15);

        jScrollPane1.setViewportView(jPanel5);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label3;
    // End of variables declaration//GEN-END:variables
}
